cloudcannon:
  data: true



uploads_dir: "assets/images"

comments:
 body_font_family: Add the font code block on the configurations menu
 heading_font_family: Add the font code block on the configuratios menu
 preview_image: Image to be shown when sharing the site on social networks

plugins:
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-postcss

webp:
  enabled: true
  nested: true
  img_dir: ["/assets/images"]
  regenerate: false
  
channels:
  - "Facebook"
  - "Instagram"
  - "Twitter"
  - "WhatsApp"
  - "Github"
  - "Snapchat"
  - "LinkedIn"
  - "Skype"
  - "Telegram"
  - "Signal"
  - "Messenger"